services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: user-management-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - user-management-network

  db:
    image: postgres:14
    container_name: user-management-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - dbdata:/var/lib/postgresql/data/pgdata
    networks:
      - user-management-network

  nginx:
    image: nginx:alpine
    container_name: user-management-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - user-management-network

networks:
  user-management-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
